#!/usr/bin/env bash
# @file make_peer_repo.sh
# @brief Build the standalone `atomfind` repository (the peer-reproduction deliverable).
#
# The standalone repo is a BUILD ARTEFACT, never hand-edited: this repo stays canonical, and
# rerunning the script regenerates it from the current HEAD. That avoids maintaining two
# diverging copies of the same package while the report is being finished.
#
# It uses `git subtree split`, so the extracted repo keeps the real commit history of
# analysis/atomfind (23 commits at time of writing) rather than arriving as one flat import.
#
#   bash analysis/atomfind/make_peer_repo.sh [DEST]        # default ~/atomfind
#
# Afterwards, to publish:
#   cd DEST && git remote add origin git@github.com:<user>/atomfind.git && git push -u origin main
set -euo pipefail

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"     # ptychoshelves-clean
DST="${1:-$HOME/atomfind}"
PREFIX="analysis/atomfind"

command -v git >/dev/null || { echo "git not found"; exit 1; }
cd "$SRC"
[ -z "$(git status --porcelain -- "$PREFIX")" ] || {
  echo "ERROR: $PREFIX has uncommitted changes -- commit them first, the split reads HEAD."
  git status --short -- "$PREFIX"; exit 1; }

echo "[1/4] splitting $PREFIX out of $(basename "$SRC") ..."
git branch -D atomfind-only >/dev/null 2>&1 || true
git subtree split --prefix="$PREFIX" -b atomfind-only >/dev/null

echo "[2/4] creating $DST ..."
rm -rf "$DST"; mkdir -p "$DST"; cd "$DST"
git init -q -b main
git pull -q "$SRC" atomfind-only

echo "[3/4] restructuring: package into atomfind/, docs at the root ..."
# The split puts the package CONTENTS at the repo root, which breaks `from atomfind import ...`.
# Move the importable package down one level; leave the reader-facing docs on top.
mkdir -p atomfind
for f in *.py data docs paper; do
  [ -e "$f" ] && git mv "$f" "atomfind/$f"
done
cat > .gitignore <<'EOF'
# Data ships as a tarball (see PEER.md); only the small prepared-GT cache is tracked.
atomfind/data/*
!atomfind/data/gt_prepared.npz

# Run outputs
atomfind_out/
out/

# Python
__pycache__/
*.py[cod]
venv/
.venv/

# OS
.DS_Store
EOF
git add -A
git commit -q -m "Repo layout: importable package under atomfind/, docs at the root

Generated by make_peer_repo.sh from the pipeline repo. The subtree split places the
package contents at the repo root, which breaks the absolute 'from atomfind import ...'
imports the modules use; moving them one level down restores them and matches the
commands documented in PEER.md."

echo "[4/4] verifying ..."
python3 - <<'PY'
import os, sys
sys.path.insert(0, os.getcwd())
import importlib
for m in ("config", "align", "psf", "deconv", "find", "fit", "validate", "uncertainty"):
    importlib.import_module(f"atomfind.{m}")
from atomfind import config
assert os.path.exists(config.data_path("gt_prepared.npz")), "GT cache missing from the split"
print("    imports OK; gt_prepared.npz present")
PY
echo
echo "Built $DST  ($(git rev-list --count HEAD) commits, $(du -sh .git | cut -f1) of history)"
echo "Data is NOT included -- build the tarball with make_peer_tarball.sh and see PEER.md."
